// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkqiklfpleoiupgfvsxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrcWlrbGZwbGVvaXVwZ2Z2c3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjgyOTQsImV4cCI6MjA2MzQwNDI5NH0.ujz3fQAkfri84qn0Ge_RaU0uatFfGhqpoBsLN98C0cI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);